/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fix_care.form;

import fix_care.clases.ConexionBD;
import fix_care.clases.Usuario;
import fix_care.clases.UsuarioBD;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author erick
 */
public class Alta_Usuario extends javax.swing.JPanel {

    String selectedImagePath = "";
    public Alta_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        radio_white1 = new fix_care.menu.radio_white();
        cmbRol = new javax.swing.JComboBox<>();
        separatorNombre = new javax.swing.JSeparator();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        separatorApePat = new javax.swing.JSeparator();
        labelApePat = new javax.swing.JLabel();
        txtApePat = new javax.swing.JTextField();
        txtApeMat = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        labelApeMat = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        labelTelefono = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        labelUsuario = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        labelPassword1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtPassword2 = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        ProfileImage = new javax.swing.JLabel();
        browseBtn = new javax.swing.JPanel();
        btnBrowse = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(843, 700));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 662));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Técnico", "Docente" }));
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        separatorNombre.setBackground(new java.awt.Color(26, 104, 177));
        separatorNombre.setForeground(new java.awt.Color(26, 104, 177));

        labelNombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(102, 102, 102));
        labelNombre.setText("NOMBRE");

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setText("Ingresa el nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });

        separatorApePat.setBackground(new java.awt.Color(26, 104, 177));
        separatorApePat.setForeground(new java.awt.Color(26, 104, 177));

        labelApePat.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelApePat.setForeground(new java.awt.Color(102, 102, 102));
        labelApePat.setText("APELLIDO PATERNO");

        txtApePat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApePat.setText("Ingresa el apellido");
        txtApePat.setBorder(null);
        txtApePat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApePatMousePressed(evt);
            }
        });
        txtApePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApePatActionPerformed(evt);
            }
        });

        txtApeMat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApeMat.setText("Ingresa el apellido");
        txtApeMat.setBorder(null);
        txtApeMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApeMatMousePressed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(26, 104, 177));
        jSeparator3.setForeground(new java.awt.Color(26, 104, 177));

        labelApeMat.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelApeMat.setForeground(new java.awt.Color(102, 102, 102));
        labelApeMat.setText("APELLIDO MATERNO");

        labelCorreo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(102, 102, 102));
        labelCorreo.setText("CORREO");

        jSeparator4.setBackground(new java.awt.Color(26, 104, 177));
        jSeparator4.setForeground(new java.awt.Color(26, 104, 177));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreo.setText("Ingresa el correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelefono.setText("Ingresa el teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(26, 104, 177));
        jSeparator5.setForeground(new java.awt.Color(26, 104, 177));

        labelTelefono.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(102, 102, 102));
        labelTelefono.setText("TELÉFONO");

        labelRol.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelRol.setForeground(new java.awt.Color(102, 102, 102));
        labelRol.setText("ROL");
        labelRol.setPreferredSize(new java.awt.Dimension(75, 18));

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsuario.setText("Ingresa el usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(26, 104, 177));
        jSeparator6.setForeground(new java.awt.Color(26, 104, 177));

        labelUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        labelUsuario.setText("USUARIO");

        labelPassword.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(102, 102, 102));
        labelPassword.setText("CONTRASEÑA");

        jSeparator7.setBackground(new java.awt.Color(26, 104, 177));
        jSeparator7.setForeground(new java.awt.Color(26, 104, 177));

        txtPassword.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPassword.setText("Ingresa la contraseña");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });

        labelPassword1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        labelPassword1.setForeground(new java.awt.Color(102, 102, 102));
        labelPassword1.setText("REPITA CONTRASEÑA");

        jSeparator8.setBackground(new java.awt.Color(26, 104, 177));
        jSeparator8.setForeground(new java.awt.Color(26, 104, 177));

        txtPassword2.setText("********");
        txtPassword2.setBorder(null);
        txtPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassword2MousePressed(evt);
            }
        });
        txtPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword2ActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(8, 55, 116));

        btnGuardar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        ProfileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix/care/images/logo.png"))); // NOI18N

        browseBtn.setBackground(new java.awt.Color(8, 55, 116));

        btnBrowse.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix/care/images/uploadIcon.png"))); // NOI18N
        btnBrowse.setText("SUBIR IMG");
        btnBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBrowseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBrowseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout browseBtnLayout = new javax.swing.GroupLayout(browseBtn);
        browseBtn.setLayout(browseBtnLayout);
        browseBtnLayout.setHorizontalGroup(
            browseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        browseBtnLayout.setVerticalGroup(
            browseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browseBtnLayout.createSequentialGroup()
                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout radio_white1Layout = new javax.swing.GroupLayout(radio_white1);
        radio_white1.setLayout(radio_white1Layout);
        radio_white1Layout.setHorizontalGroup(
            radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
            .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(radio_white1Layout.createSequentialGroup()
                    .addGap(0, 222, Short.MAX_VALUE)
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(ProfileImage)
                            .addGap(40, 40, 40)
                            .addComponent(browseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(labelNombre)
                            .addGap(149, 149, 149)
                            .addComponent(labelApePat)
                            .addGap(68, 68, 68)
                            .addComponent(labelApeMat))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(separatorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(separatorApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(labelCorreo)
                            .addGap(150, 150, 150)
                            .addComponent(labelTelefono)
                            .addGap(144, 144, 144)
                            .addComponent(labelRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(labelUsuario)
                            .addGap(147, 147, 147)
                            .addComponent(labelPassword)
                            .addGap(122, 122, 122)
                            .addComponent(labelPassword1))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 223, Short.MAX_VALUE)))
        );
        radio_white1Layout.setVerticalGroup(
            radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(radio_white1Layout.createSequentialGroup()
                    .addGap(0, 89, Short.MAX_VALUE)
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ProfileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(browseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(30, 30, 30)
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelNombre)
                        .addComponent(labelApePat)
                        .addComponent(labelApeMat))
                    .addGap(11, 11, 11)
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(separatorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(separatorApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelCorreo)
                        .addComponent(labelTelefono)
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(labelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(1, 1, 1)
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(radio_white1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelUsuario)
                        .addComponent(labelPassword)
                        .addComponent(labelPassword1))
                    .addGap(11, 11, 11)
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 90, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio_white1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(radio_white1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if (txtNombre.getText().equals("Ingresa el nombre")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApePatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApePatMousePressed
        if (txtApePat.getText().equals("Ingresa el apellido")) {
            txtApePat.setText("");
            txtApePat.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtApePatMousePressed

    private void txtApeMatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApeMatMousePressed
  if (txtApeMat.getText().equals("Ingresa el apellido")) {
            txtApeMat.setText("");
            txtApeMat.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtApeMatMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if (txtCorreo.getText().equals("Ingresa el correo")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
         if (txtTelefono.getText().equals("Ingresa el teléfono")) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
if (txtUsuario.getText().equals("Ingresa el usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
if (txtPassword.getText().equals("Ingresa la contraseña")) {
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordMousePressed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
    
        String nombre=txtNombre.getText();
        String apepat=txtApePat.getText();
        String apemat=txtApeMat.getText();
        String correo=txtCorreo.getText();
        String telefono=txtTelefono.getText();
        String pass =txtPassword.getText();        
        String usuario=txtUsuario.getText();  
        int rol=cmbRol.getSelectedIndex();
        String roltxt="";
        System.out.println(rol);
        switch (rol) {
            case 0:
            roltxt="Administrador";    
            break;
            case 1:
            roltxt="Técnico";    
            break;
            case 2:
            roltxt="Docente";       
            break;
            default:
            roltxt="Error";       
        }
        if(!pass.equals(new String(txtPassword2.getPassword())))
        {
        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden ingrese de nuevo");
        txtPassword2.setText("");
        }
        else{
         Usuario  objUsuario = new Usuario(nombre, apepat, apemat, correo, roltxt, telefono, usuario, pass, selectedImagePath);
         if(this.insertarUsuario(objUsuario)){
         }
        }
        
                              
       
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private boolean insertarUsuario(Usuario user){
    boolean ingresado = false;  //variable de retorno en caso de ser falso o verdadero
        Connection conn;   // objeto de conexion
        PreparedStatement stmt = null;   // variable para la sentencia sql
       
    //aqui se conectara a la base de datos y se buscara el usuario en la tabla de usuarios del sistema para su comparacion
      try {
            ConexionBD   objetoConexionBD = new ConexionBD();
            conn=  objetoConexionBD.conexionDataBase();                
            UsuarioBD bd = new UsuarioBD();
            int idGenerado = bd.insertUser(conn,user);
                 
             if (idGenerado>=1) {  //encontro al menos 1 registro con los datos
                //accedemos al sistema
                ingresado = true;
                JOptionPane.showMessageDialog(this, "El Ususario "+user.getNombre()+" ha sido guardado con éxito");
            }   
              //se cierra la conexion
              objetoConexionBD.cerrarConexion(conn);
             
        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión " +
                    ex.getMessage());
        }
    //regresamos si el usuario se localizo
    return ingresado;
    
    
    }
    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        loginBtn.setBackground(new Color(33,161,153));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        loginBtn.setBackground(new Color(8, 55, 116));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void txtApePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApePatActionPerformed

    private void txtPassword2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword2MousePressed
        if (String.valueOf(txtPassword2.getPassword()).equals("********")) {
            txtPassword2.setText("");
            txtPassword2.setForeground(Color.black);
        }
        if (txtPassword.getText().isEmpty()) {
            txtPassword.setText("Sin coincidencia");
            txtPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPassword2MousePressed

    private void txtPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword2ActionPerformed

    private void btnBrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseMouseClicked
        JFileChooser browseImageFile = new JFileChooser();
        //Filtrar imagenes
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg"); //Tipo de archivos permisibles 
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
         File selectedImageFile = browseImageFile.getSelectedFile();
         selectedImagePath = selectedImageFile.getAbsolutePath();
       //  JOptionPane.showMessageDialog(null, selectedImagePath);
         //Despliega las imagenes el el jlabel
         ImageIcon ii = new ImageIcon(selectedImagePath);
         //Ajustamos la imagen
         Image image = ii.getImage().getScaledInstance(ProfileImage.getWidth(), ProfileImage.getHeight(), Image.SCALE_SMOOTH);
         ProfileImage.setIcon(new ImageIcon(image));
        }
        
    }//GEN-LAST:event_btnBrowseMouseClicked

    private void btnBrowseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseMouseEntered

    private void btnBrowseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProfileImage;
    private javax.swing.JPanel browseBtn;
    private javax.swing.JLabel btnBrowse;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel labelApeMat;
    private javax.swing.JLabel labelApePat;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPassword1;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel loginBtn;
    private fix_care.menu.radio_white radio_white1;
    private javax.swing.JSeparator separatorApePat;
    private javax.swing.JSeparator separatorNombre;
    private javax.swing.JTextField txtApeMat;
    private javax.swing.JTextField txtApePat;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
