/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package fix_care.form;
import fix_care.clases.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class Alta_Departamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alta_Departamento
     */
    public Alta_Departamento() {
        initComponents();
        cargarEncargados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEncargado = new javax.swing.JLabel();
        cmbEncargado = new javax.swing.JComboBox<>();
        labelEdificio = new javax.swing.JLabel();
        loginBtn = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        cmbEdificios = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Alta de Departamento"));
        setForeground(new java.awt.Color(187, 187, 187));
        setDoubleBuffered(true);
        setFocusCycleRoot(false);
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(902, 598));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(997, 646));

        labelEncargado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEncargado.setForeground(new java.awt.Color(102, 102, 102));
        labelEncargado.setText("Encargado:");

        cmbEncargado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEncargado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEncargadoActionPerformed(evt);
            }
        });

        labelEdificio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEdificio.setText("Edificio:");

        loginBtn.setBackground(new java.awt.Color(8, 55, 116));

        btnGuardar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmbEdificios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEdificio)
                            .addComponent(cmbEdificios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEncargado)
                            .addComponent(cmbEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelEdificio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEdificios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEncargado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getAccessibleContext().setAccessibleName("Alta de Departamento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarEncargados() {
        Connection conn = null;
        try {
            // Creamos una instancia de tu clase de conexión
            ConexionBD objConexion = new ConexionBD();
            // Llamamos al método de instancia para obtener la conexión
            conn = objConexion.conexionDataBase();
            
            // Validamos que la conexión no sea nula antes de usarla
            if (conn != null) {
                String sql = "SELECT idUsuario, nombre FROM usuario";
                try (PreparedStatement stmt = conn.prepareStatement(sql);
                     ResultSet rs = stmt.executeQuery()) {
                    while (rs.next()) {
                        int id = rs.getInt("idUsuario");
                        String nombre = rs.getString("nombre");
                        cmbEncargado.addItem(id + " - " + nombre);
                    }
                }
            } else {
                 JOptionPane.showMessageDialog(this, "No se pudo establecer la conexión a la base de datos.", "Error de conexión", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar encargados: " + e.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Aseguramos que la conexión se cierre al final
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    System.err.println("Error al cerrar la conexión: " + e.getMessage());
                }
            }
        }
    }
    
    
    /*private void guardarDepartamento() {
    String encargadoSeleccionado = (String) cmbEncargado.getSelectedItem();
        //String departamentoTexto = cmbEdificios
        
        // Validar que se haya seleccionado un encargado y se haya escrito un nombre de departamento
        if (encargadoSeleccionado == null || encargadoSeleccionado.isEmpty() || departamentoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un encargado y escriba el nombre del departamento.", "Error de validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Extraer el ID del encargado del string seleccionado en el JComboBox
        int idEncargado = Integer.parseInt(encargadoSeleccionado.split(" - ")[0]);

        Connection conn = null;
        try {
            // Creamos una instancia de tu clase de conexión
            ConexionBD objConexion = new ConexionBD();
            // Llamamos al método de instancia para obtener la conexión
            conn = objConexion.conexionDataBase();

            if (conn != null) {
                String sql = "INSERT INTO departamento (idUsuario, nombreDepartamento) VALUES (?, ?)";
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setInt(1, idEncargado);
                    stmt.setString(2, departamentoTexto);
                    stmt.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this, "Departamento registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    
                    // Limpiar los campos después de guardar
                    txtEdificio.setText("");
                    // No necesitas cmbEncargado.setSelectedIndex(0) porque el formulario se recarga en el constructor.
                }
            } else {
                 JOptionPane.showMessageDialog(this, "No se pudo establecer la conexión a la base de datos.", "Error de conexión", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el departamento: " + e.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Aseguramos que la conexión se cierre al final
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    System.err.println("Error al cerrar la conexión: " + e.getMessage());
                }
            }
        }
}*/
    
    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        loginBtn.setBackground(new Color(33,161,153));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        loginBtn.setBackground(new Color(8, 55, 116));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void cmbEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEncargadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JComboBox<String> cmbEdificios;
    private javax.swing.JComboBox<String> cmbEncargado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEdificio;
    private javax.swing.JLabel labelEncargado;
    private javax.swing.JPanel loginBtn;
    // End of variables declaration//GEN-END:variables
}
