/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fix_care.form;

import fix_care.clases.ConexionBD;
import fix_care.clases.TicketBD;
import fix_care.clases.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class Consulta extends javax.swing.JPanel {
ConexionBD objetoConexionBD = new ConexionBD(); //Creación del objeto de base de datos
Connection conn; //Objeto de conexión
PreparedStatement stmt = null; //variable para la sentencia sql
ResultSet rs = null; //Variable para resultado de consulta sql 
    Usuario user;
    String rol="";
    public Consulta(Usuario user) {
       
        initComponents();
        this.user=user;
        rol=this.user.getRol();
        
        if(rol.equals("Administrador"))
        {
            CmbConsultaUsuario.setVisible(false);
            
        }
        else{
            CmbConsultaAdmi.setVisible(false); 
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pruebagradiant1 = new fix_care.menu.pruebagradiant();
        titulo = new javax.swing.JLabel();
        logo_fix = new javax.swing.JLabel();
        LabelTituloNombre = new javax.swing.JLabel();
        CmbConsultaAdmi = new javax.swing.JComboBox<>();
        txtRellenar = new javax.swing.JTextField();
        CmbConsultaUsuario = new javax.swing.JComboBox<>();
        save_ticket = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        radio_white1 = new fix_care.menu.radio_white();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new fix_care.swing.table.Table();

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));

        pruebagradiant1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix/care/images/001-buscar.png"))); // NOI18N
        titulo.setText("CONSULTA");
        titulo.setPreferredSize(new java.awt.Dimension(75, 18));
        pruebagradiant1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 6, 168, 45));

        logo_fix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix/care/images/text_logo.png"))); // NOI18N
        logo_fix.setText("jLabel2");
        pruebagradiant1.add(logo_fix, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 72, 266, 72));

        LabelTituloNombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LabelTituloNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelTituloNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix/care/images/001-consulta.png"))); // NOI18N
        LabelTituloNombre.setText("BUSCAR POR: ");
        LabelTituloNombre.setPreferredSize(new java.awt.Dimension(75, 18));
        pruebagradiant1.add(LabelTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 63, 220, 20));

        CmbConsultaAdmi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Folio", "Solicitante", "Servicio", "Tecnico", "Problematica " }));
        pruebagradiant1.add(CmbConsultaAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 101, 131, -1));

        txtRellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRellenarActionPerformed(evt);
            }
        });
        pruebagradiant1.add(txtRellenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 101, 160, -1));

        CmbConsultaUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Folio", "Servicio ", "Problematica" }));
        CmbConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbConsultaUsuarioActionPerformed(evt);
            }
        });
        pruebagradiant1.add(CmbConsultaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 131, -1));

        save_ticket.setBackground(new java.awt.Color(8, 55, 116));

        btnGuardar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix/care/images/002-guardar-el-archivo_1.png"))); // NOI18N
        btnGuardar.setText("BUSCAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout save_ticketLayout = new javax.swing.GroupLayout(save_ticket);
        save_ticket.setLayout(save_ticketLayout);
        save_ticketLayout.setHorizontalGroup(
            save_ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        save_ticketLayout.setVerticalGroup(
            save_ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pruebagradiant1.add(save_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 191, -1, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Folio", "Solicitante", "Edificio", "Area", "Servicio", "Fecha", "Estado", "Problematica", "Tecnico", "Bitacora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout radio_white1Layout = new javax.swing.GroupLayout(radio_white1);
        radio_white1.setLayout(radio_white1Layout);
        radio_white1Layout.setHorizontalGroup(
            radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radio_white1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        radio_white1Layout.setVerticalGroup(
            radio_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radio_white1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_white1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pruebagradiant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pruebagradiant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radio_white1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRellenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRellenarActionPerformed

    private void CmbConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbConsultaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbConsultaUsuarioActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

    try {
        this.rellenarTablaConsulta();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
    }
             
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
    
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
    
    }//GEN-LAST:event_btnGuardarMouseExited
public final void rellenarTablaConsulta() throws ClassNotFoundException, SQLException {
        if(rol.equals("Admininstrador")){
        conn = objetoConexionBD.conexionDataBase();
        String combo = CmbConsultaAdmi.getSelectedItem().toString();
        String variable = txtRellenar.getText().trim();
        TicketBD objTicket = new TicketBD();
        //Actualizar tabla 
    DefaultTableModel modelo = (DefaultTableModel) table1.getModel();
    modelo.setRowCount(0); //Limpiar Tabla
        rs = objTicket.rellenarTablaConsulta(conn, combo, variable);
        while (rs.next()) {
            table1.addRow(new Object[]{rs.getString("folio"), rs.getString("solicitante"), rs.getString("Edificio"), rs.getString("area"), rs.getString("servicio"), rs.getString("fecha"), rs.getString("estado"), rs.getString("problematica"), rs.getString("tecnico"), rs.getString("bitacora")});
        }
        objetoConexionBD.cerrarConexion(conn);
        }
        else{
        conn = objetoConexionBD.conexionDataBase();
        String combo = CmbConsultaUsuario.getSelectedItem().toString();
        String variable = txtRellenar.getText().trim();
        TicketBD objTicket = new TicketBD();
        //Actualizar tabla 
    DefaultTableModel modelo = (DefaultTableModel) table1.getModel();
    modelo.setRowCount(0); //Limpiar Tabla
        rs = objTicket.rellenarTablaConsulta(conn, combo, variable);
        while (rs.next()) {
            table1.addRow(new Object[]{rs.getString("folio"), rs.getString("solicitante"), rs.getString("Edificio"), rs.getString("area"), rs.getString("servicio"), rs.getString("fecha"), rs.getString("estado"), rs.getString("problematica"), rs.getString("tecnico"), rs.getString("bitacora")});
        }
        objetoConexionBD.cerrarConexion(conn);
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbConsultaAdmi;
    private javax.swing.JComboBox<String> CmbConsultaUsuario;
    private javax.swing.JLabel LabelTituloNombre;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_fix;
    private fix_care.menu.pruebagradiant pruebagradiant1;
    private fix_care.menu.radio_white radio_white1;
    private javax.swing.JPanel save_ticket;
    private fix_care.swing.table.Table table1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtRellenar;
    // End of variables declaration//GEN-END:variables
}
